development:
  database:
    name: soarec_development
    host: 172.17.0.2
    port: 27017

test:
  database:
    name: soarec_test
    host: 127.0.0.1
    port: 27017

production:
  database:
    name: soarec
    host: 127.0.0.1
    port: 27017
